meta_product_name: "Cocoon Clothing"
meta_title: "Cocoon Clothing - Just the coolest shirt brand in Belgium..."
meta_description: "“The Cocoon Shirt” is the iconic summer shirt, 100% made in Belgium. The fifteen different motifs will vary from simple plain colours to crazy and folkloric patterns. "
#meta_image: "P1040429.jpg"                       # should exist in `app/assets/images/`
#twitter_account: "@product_twitter_account"
